.Dd July 20, 2015
.Dt dynamic_cast 1
.Os
.Sh NAME
.Nm dynamic_cast
.Nd Test C++ dynamic_cast feature of the runtime C++11 library
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
This utility tests how C++ dynamic_cast<Child*> casting works across
shared modules linked at run-time.
.Sh AUTHOR
Marcin Cieslak <saper@saper.info>
